-- CLEANED

INSERT INTO characters (id, name) VALUES ('1440', 'Wolverine');
INSERT INTO characters (id, name) VALUES ('1441', 'Magneto');
INSERT INTO characters (id, name) VALUES ('1442', 'Captain America');
INSERT INTO characters (id, name) VALUES ('1443', 'Spider-Man');
INSERT INTO characters (id, name) VALUES ('1444', 'Storm');
INSERT INTO characters (id, name) VALUES ('1446', 'Rogue');
INSERT INTO characters (id, name) VALUES ('1449', 'She-Hulk');
INSERT INTO characters (id, name) VALUES ('1451', 'Sam Wilson');
INSERT INTO characters (id, name) VALUES ('1455', 'Iron Man');
INSERT INTO characters (id, name) VALUES ('1456', 'Doctor Strange');
INSERT INTO characters (id, name) VALUES ('1460', 'Colossus');
INSERT INTO characters (id, name) VALUES ('1461', 'Nightcrawler');
INSERT INTO characters (id, name) VALUES ('1462', 'Beast');
INSERT INTO characters (id, name) VALUES ('1464', 'Iceman');
INSERT INTO characters (id, name) VALUES ('1465', 'Wonder Man');
INSERT INTO characters (id, name) VALUES ('1466', 'Scarlet Witch');
INSERT INTO characters (id, name) VALUES ('1467', 'Quicksilver');
INSERT INTO characters (id, name) VALUES ('1468', 'Doctor Doom');
INSERT INTO characters (id, name) VALUES ('1475', 'Hawkeye');
INSERT INTO characters (id, name) VALUES ('1477', 'Black Panther');
INSERT INTO characters (id, name) VALUES ('1492', 'Iron Fist');
INSERT INTO characters (id, name) VALUES ('1502', 'Wasp');
INSERT INTO characters (id, name) VALUES ('1504', 'Vision');
INSERT INTO characters (id, name) VALUES ('1525', 'Punisher');
INSERT INTO characters (id, name) VALUES ('1526', 'Microchip');
INSERT INTO characters (id, name) VALUES ('1686', 'Kon-El');
INSERT INTO characters (id, name) VALUES ('1691', 'Dick Grayson');
INSERT INTO characters (id, name) VALUES ('1698', 'Catwoman');
INSERT INTO characters (id, name) VALUES ('1699', 'Batman');
INSERT INTO characters (id, name) VALUES ('1702', 'Joker');
INSERT INTO characters (id, name) VALUES ('1807', 'Superman');
INSERT INTO characters (id, name) VALUES ('1808', 'Lois Lane');
INSERT INTO characters (id, name) VALUES ('1809', 'Perry White');
INSERT INTO characters (id, name) VALUES ('1945', 'Swarm');
INSERT INTO characters (id, name) VALUES ('2031', 'Steel');
INSERT INTO characters (id, name) VALUES ('2047', 'Martian Manhunter');
INSERT INTO characters (id, name) VALUES ('2048', 'Wonder Woman');
INSERT INTO characters (id, name) VALUES ('2105', 'Nova');
INSERT INTO characters (id, name) VALUES ('2114', 'Thing');
INSERT INTO characters (id, name) VALUES ('2115', 'Crystal');
INSERT INTO characters (id, name) VALUES ('2120', 'Human Torch');
INSERT INTO characters (id, name) VALUES ('2149', 'Galactus');
INSERT INTO characters (id, name) VALUES ('2222', 'Lady Shiva');
INSERT INTO characters (id, name) VALUES ('2242', 'Ultron');
INSERT INTO characters (id, name) VALUES ('2252', 'Wrecker');
INSERT INTO characters (id, name) VALUES ('2264', 'Kang');
INSERT INTO characters (id, name) VALUES ('2268', 'Thor');
INSERT INTO characters (id, name) VALUES ('2349', 'Darkseid');
INSERT INTO characters (id, name) VALUES ('2350', 'Billy Batson');
INSERT INTO characters (id, name) VALUES ('2351', 'Supergirl');
INSERT INTO characters (id, name) VALUES ('2357', 'Aquaman');
INSERT INTO characters (id, name) VALUES ('2361', 'Spectre');
INSERT INTO characters (id, name) VALUES ('2380', 'Gorilla Grodd');
INSERT INTO characters (id, name) VALUES ('2388', 'Cyborg');
INSERT INTO characters (id, name) VALUES ('2389', 'Starfire');
INSERT INTO characters (id, name) VALUES ('2481', 'Mole Man');
INSERT INTO characters (id, name) VALUES ('2497', 'Mockingbird');
INSERT INTO characters (id, name) VALUES ('2503', 'Hercules');
INSERT INTO characters (id, name) VALUES ('2594', 'R2-D2');
INSERT INTO characters (id, name) VALUES ('2608', 'Han Solo');
INSERT INTO characters (id, name) VALUES ('3213', 'Jimmy Olsen');
INSERT INTO characters (id, name) VALUES ('3229', 'Count Nefaria');
INSERT INTO characters (id, name) VALUES ('3318', 'Jocasta');
INSERT INTO characters (id, name) VALUES ('3327', 'Agatha Harkness');
INSERT INTO characters (id, name) VALUES ('3404', 'Roy Harper');
INSERT INTO characters (id, name) VALUES ('3552', 'Jean Grey');
INSERT INTO characters (id, name) VALUES ('3560', 'X-23');
INSERT INTO characters (id, name) VALUES ('3588', 'Deathstroke');
INSERT INTO characters (id, name) VALUES ('3602', 'Thomas Wayne');
INSERT INTO characters (id, name) VALUES ('3603', 'Martha Wayne');
INSERT INTO characters (id, name) VALUES ('3617', 'Jonathan Kent');
INSERT INTO characters (id, name) VALUES ('3618', 'Martha Kent');
INSERT INTO characters (id, name) VALUES ('3715', 'Mr. Freeze');
INSERT INTO characters (id, name) VALUES ('3718', 'Riddler');
INSERT INTO characters (id, name) VALUES ('3724', 'Black Mask');
INSERT INTO characters (id, name) VALUES ('3725', 'Killer Croc');
INSERT INTO characters (id, name) VALUES ('3726', 'Scarecrow');
INSERT INTO characters (id, name) VALUES ('3727', 'James Gordon');
INSERT INTO characters (id, name) VALUES ('3738', 'Lucius Fox');
INSERT INTO characters (id, name) VALUES ('3771', 'Pete Ross');
INSERT INTO characters (id, name) VALUES ('4324', 'Loki');
INSERT INTO characters (id, name) VALUES ('4326', 'Ebony');
INSERT INTO characters (id, name) VALUES ('4327', 'Medusa');
INSERT INTO characters (id, name) VALUES ('4689', 'Metallo');
INSERT INTO characters (id, name) VALUES ('4690', 'Parasite');
INSERT INTO characters (id, name) VALUES ('4701', 'General Darnell');
INSERT INTO characters (id, name) VALUES ('4906', 'Fury (Hall)');
INSERT INTO characters (id, name) VALUES ('4915', 'Power Girl');
INSERT INTO characters (id, name) VALUES ('4918', 'Dr. Psycho');
INSERT INTO characters (id, name) VALUES ('4929', 'Hippolyta');
INSERT INTO characters (id, name) VALUES ('4935', 'Johnny Thunder');
INSERT INTO characters (id, name) VALUES ('5368', 'Barbara Gordon');
INSERT INTO characters (id, name) VALUES ('5547', 'Lana Lang');
INSERT INTO characters (id, name) VALUES ('5554', 'Harvey Bullock');
INSERT INTO characters (id, name) VALUES ('5555', 'Two-Face');
INSERT INTO characters (id, name) VALUES ('5556', 'Alfred Pennyworth');
INSERT INTO characters (id, name) VALUES ('5703', 'Mr. Miracle');
INSERT INTO characters (id, name) VALUES ('5814', 'Mad Hatter');
INSERT INTO characters (id, name) VALUES ('5936', 'Green Arrow');
INSERT INTO characters (id, name) VALUES ('6090', 'Fang');
INSERT INTO characters (id, name) VALUES ('6096', 'Supreme Intelligence');
INSERT INTO characters (id, name) VALUES ('6129', 'Bane');
INSERT INTO characters (id, name) VALUES ('6131', 'Man-Bat');
INSERT INTO characters (id, name) VALUES ('6334', 'Chewbacca');
INSERT INTO characters (id, name) VALUES ('6335', 'C-3PO');
INSERT INTO characters (id, name) VALUES ('6342', 'Darth Vader');
INSERT INTO characters (id, name) VALUES ('6599', 'Kent Nelson');
INSERT INTO characters (id, name) VALUES ('6666', 'Green Lama');
INSERT INTO characters (id, name) VALUES ('6790', 'Vapor');
INSERT INTO characters (id, name) VALUES ('6806', 'Gamora');
INSERT INTO characters (id, name) VALUES ('6807', 'Drax the Destroyer');
INSERT INTO characters (id, name) VALUES ('6820', 'Vector');
INSERT INTO characters (id, name) VALUES ('6821', 'Ironclad');
INSERT INTO characters (id, name) VALUES ('6822', 'X-Ray');
INSERT INTO characters (id, name) VALUES ('6849', 'Jason Todd');
INSERT INTO characters (id, name) VALUES ('6852', 'Jack Drake');
INSERT INTO characters (id, name) VALUES ('6903', 'Hawkgirl');
INSERT INTO characters (id, name) VALUES ('6911', 'Hyperion');
INSERT INTO characters (id, name) VALUES ('6952', 'Kilowog');
INSERT INTO characters (id, name) VALUES ('7227', 'Grim Reaper');
INSERT INTO characters (id, name) VALUES ('7229', 'Master Pandemonium');
INSERT INTO characters (id, name) VALUES ('7280', 'Death of the Endless');
INSERT INTO characters (id, name) VALUES ('7606', 'Deadpool');
INSERT INTO characters (id, name) VALUES ('7607', 'Thanos');
INSERT INTO characters (id, name) VALUES ('7645', 'Wildcat');
INSERT INTO characters (id, name) VALUES ('8264', 'Vicki Vale');
INSERT INTO characters (id, name) VALUES ('8303', 'Magik');
INSERT INTO characters (id, name) VALUES ('8332', 'Krypto');
INSERT INTO characters (id, name) VALUES ('8337', 'Hawkman');
INSERT INTO characters (id, name) VALUES ('9290', 'Tim Drake');
INSERT INTO characters (id, name) VALUES ('9296', 'Ted Knight');
INSERT INTO characters (id, name) VALUES ('9298', 'Al Pratt');
INSERT INTO characters (id, name) VALUES ('9299', 'Wesley Dodds');
INSERT INTO characters (id, name) VALUES ('9301', 'Charles M McNider');
INSERT INTO characters (id, name) VALUES ('9381', 'Snoopy');
INSERT INTO characters (id, name) VALUES ('9555', 'Destiny of the Endless');
INSERT INTO characters (id, name) VALUES ('9561', 'Jor-El');
INSERT INTO characters (id, name) VALUES ('9562', 'Lara Lor-Van');
INSERT INTO characters (id, name) VALUES ('9671', 'Adolf Hitler');
INSERT INTO characters (id, name) VALUES ('9672', 'Benito Mussolini');
INSERT INTO characters (id, name) VALUES ('9673', 'Hideki Tojo');
INSERT INTO characters (id, name) VALUES ('9977', 'Iris West Allen');
INSERT INTO characters (id, name) VALUES ('9989', 'Doomsday');
INSERT INTO characters (id, name) VALUES ('10032', 'Black Racer');
INSERT INTO characters (id, name) VALUES ('10445', 'Katma Tui');
INSERT INTO characters (id, name) VALUES ('10449', 'Tomar Re');
INSERT INTO characters (id, name) VALUES ('10451', 'John Stewart');
INSERT INTO characters (id, name) VALUES ('10476', 'Goldface');
INSERT INTO characters (id, name) VALUES ('10697', 'Anarky');
INSERT INTO characters (id, name) VALUES ('10883', 'Doctor Poison');
INSERT INTO characters (id, name) VALUES ('10957', 'Star-Lord');
INSERT INTO characters (id, name) VALUES ('11202', 'Hal Jordan');
INSERT INTO characters (id, name) VALUES ('11304', 'Salaak');
INSERT INTO characters (id, name) VALUES ('11337', 'Monica Rambeau');
INSERT INTO characters (id, name) VALUES ('11503', 'Bova');
INSERT INTO characters (id, name) VALUES ('11609', 'Giganto');
INSERT INTO characters (id, name) VALUES ('12337', 'Jane Foster');
INSERT INTO characters (id, name) VALUES ('12399', 'King Snake');
INSERT INTO characters (id, name) VALUES ('13048', 'General Sam Lane');
INSERT INTO characters (id, name) VALUES ('14399', 'Queen Marlena');
INSERT INTO characters (id, name) VALUES ('14422', 'Whizzer (Frank)');
INSERT INTO characters (id, name) VALUES ('14467', 'Korvac');
INSERT INTO characters (id, name) VALUES ('15789', 'Steve Trevor');
INSERT INTO characters (id, name) VALUES ('15790', 'Etta Candy');
INSERT INTO characters (id, name) VALUES ('16165', 'Nien Nunb');
INSERT INTO characters (id, name) VALUES ('16332', 'Cynthia');
INSERT INTO characters (id, name) VALUES ('16334', 'Mildred');
INSERT INTO characters (id, name) VALUES ('16423', 'He-Man');
INSERT INTO characters (id, name) VALUES ('16424', 'Skeletor');
INSERT INTO characters (id, name) VALUES ('16425', 'Battle Cat');
INSERT INTO characters (id, name) VALUES ('16426', 'Man-At-Arms');
INSERT INTO characters (id, name) VALUES ('16427', 'Teela');
INSERT INTO characters (id, name) VALUES ('16428', 'Zodac');
INSERT INTO characters (id, name) VALUES ('16432', 'Beast-Man');
INSERT INTO characters (id, name) VALUES ('16436', 'Mer-Man');
INSERT INTO characters (id, name) VALUES ('16817', 'Hugo Strange');
INSERT INTO characters (id, name) VALUES ('18113', 'Paul Revere');
INSERT INTO characters (id, name) VALUES ('18674', 'Aphrodite');
INSERT INTO characters (id, name) VALUES ('19682', 'Calendar Man');
INSERT INTO characters (id, name) VALUES ('19936', 'Ego');
INSERT INTO characters (id, name) VALUES ('21194', 'Adora');
INSERT INTO characters (id, name) VALUES ('21332', 'Super-Skrull');
INSERT INTO characters (id, name) VALUES ('21561', 'Carol Danvers');
INSERT INTO characters (id, name) VALUES ('22143', 'Santa Claus');
INSERT INTO characters (id, name) VALUES ('22804', 'Barry Allen');
INSERT INTO characters (id, name) VALUES ('22953', 'Lynx');
INSERT INTO characters (id, name) VALUES ('23778', 'Baroness Paula Von Gunther');
INSERT INTO characters (id, name) VALUES ('24341', 'Groot');
INSERT INTO characters (id, name) VALUES ('24694', 'Daredevil');
INSERT INTO characters (id, name) VALUES ('26050', 'Mala');
INSERT INTO characters (id, name) VALUES ('26147', 'Father Time');
INSERT INTO characters (id, name) VALUES ('26635', 'Rupert Thorne');
INSERT INTO characters (id, name) VALUES ('27246', 'Krona');
INSERT INTO characters (id, name) VALUES ('28117', 'King Randor');
INSERT INTO characters (id, name) VALUES ('31684', 'Hermann Göring');
INSERT INTO characters (id, name) VALUES ('31685', 'Joseph Goebbels');
INSERT INTO characters (id, name) VALUES ('32355', 'The Squid');
INSERT INTO characters (id, name) VALUES ('32398', 'Hamilton Hill');
INSERT INTO characters (id, name) VALUES ('32400', 'Olivia Ortega');
INSERT INTO characters (id, name) VALUES ('32536', 'Peter Pauling');
INSERT INTO characters (id, name) VALUES ('32589', 'Arthur Reeves');
INSERT INTO characters (id, name) VALUES ('32590', 'The Sorceress');
INSERT INTO characters (id, name) VALUES ('32592', 'Hirohito');
INSERT INTO characters (id, name) VALUES ('32676', 'Dala');
INSERT INTO characters (id, name) VALUES ('33126', 'Thunderbolt');
INSERT INTO characters (id, name) VALUES ('33545', 'Princess Leia');
INSERT INTO characters (id, name) VALUES ('33682', 'Dr. Albert Ekhart');
INSERT INTO characters (id, name) VALUES ('34109', 'Omega the Unknown');
INSERT INTO characters (id, name) VALUES ('34271', 'Gloria Rider');
INSERT INTO characters (id, name) VALUES ('34685', 'Ray Palmer');
INSERT INTO characters (id, name) VALUES ('35547', 'Monark Starstalker');
INSERT INTO characters (id, name) VALUES ('36452', 'George Washington');
INSERT INTO characters (id, name) VALUES ('38634', 'Benjamin Franklin');
INSERT INTO characters (id, name) VALUES ('39462', 'Nora Allen');
INSERT INTO characters (id, name) VALUES ('39780', 'Humpty Dumpty');
INSERT INTO characters (id, name) VALUES ('40586', 'Glob Herman');
INSERT INTO characters (id, name) VALUES ('41359', 'Ch''p');
INSERT INTO characters (id, name) VALUES ('41919', 'Mogo');
INSERT INTO characters (id, name) VALUES ('41952', 'Lex Luthor');
INSERT INTO characters (id, name) VALUES ('42290', 'Gilda Dent');
INSERT INTO characters (id, name) VALUES ('42413', 'Damian Wayne');
INSERT INTO characters (id, name) VALUES ('42582', 'Salvatore Maroni');
INSERT INTO characters (id, name) VALUES ('45563', 'Huntress (Wayne)');
INSERT INTO characters (id, name) VALUES ('46423', 'Chaselon');
INSERT INTO characters (id, name) VALUES ('47249', 'Hypnota');
INSERT INTO characters (id, name) VALUES ('47281', 'Green Man');
INSERT INTO characters (id, name) VALUES ('49716', 'Oliversity');
INSERT INTO characters (id, name) VALUES ('51594', 'Worldmind');
INSERT INTO characters (id, name) VALUES ('52823', 'Janet Drake');
INSERT INTO characters (id, name) VALUES ('53653', 'Obeah Man');
INSERT INTO characters (id, name) VALUES ('56661', 'Barack Obama');
INSERT INTO characters (id, name) VALUES ('56849', 'Duke of Deception');
INSERT INTO characters (id, name) VALUES ('60461', 'Mordred');
INSERT INTO characters (id, name) VALUES ('60712', 'Iroque');
INSERT INTO characters (id, name) VALUES ('62833', 'Kal-L');
INSERT INTO characters (id, name) VALUES ('63206', 'Mars');
INSERT INTO characters (id, name) VALUES ('64661', 'Earl of Greed');
INSERT INTO characters (id, name) VALUES ('64690', 'Lord Conquest');
INSERT INTO characters (id, name) VALUES ('67267', 'Hercules');
INSERT INTO characters (id, name) VALUES ('67350', 'Munk');
INSERT INTO characters (id, name) VALUES ('70041', 'Athena');
INSERT INTO characters (id, name) VALUES ('70561', 'Barbara Kean');
INSERT INTO characters (id, name) VALUES ('74883', 'The Red Baron');
INSERT INTO characters (id, name) VALUES ('77549', 'Circe');
INSERT INTO characters (id, name) VALUES ('81180', 'Katar Hol');
INSERT INTO characters (id, name) VALUES ('90132', 'Mongul the Elder');
