CREATE TABLE "characters" (
"id" INTEGER,
  "name" TEXT
);

INSERT INTO characters (id, name) VALUES ('2012', 'Hiram Lodge');
INSERT INTO characters (id, name) VALUES ('2015', 'Mr. Weatherbee');
INSERT INTO characters (id, name) VALUES ('2018', 'Emerald Eyes');
INSERT INTO characters (id, name) VALUES ('2021', 'Mandala');
INSERT INTO characters (id, name) VALUES ('2022', 'Bad Jack Keller');
INSERT INTO characters (id, name) VALUES ('2024', 'MCP');
INSERT INTO characters (id, name) VALUES ('2025', 'Alice Cooper');
INSERT INTO characters (id, name) VALUES ('2026', 'Dr. Jim Murray');
INSERT INTO characters (id, name) VALUES ('2027', 'Nurse Liz Thorpe');
INSERT INTO characters (id, name) VALUES ('2030', 'Hank Hall');
INSERT INTO characters (id, name) VALUES ('2031', 'Steel');
INSERT INTO characters (id, name) VALUES ('2032', 'Anthro');
INSERT INTO characters (id, name) VALUES ('2033', 'Nighthawk');
INSERT INTO characters (id, name) VALUES ('2034', 'El Diablo');
INSERT INTO characters (id, name) VALUES ('2035', 'Lady Blackhawk');
INSERT INTO characters (id, name) VALUES ('2036', 'Kari Limbo');
INSERT INTO characters (id, name) VALUES ('2038', 'Buck Wargo');
INSERT INTO characters (id, name) VALUES ('2039', 'Esperanza Chata');
INSERT INTO characters (id, name) VALUES ('2040', 'Veronna');
INSERT INTO characters (id, name) VALUES ('2041', 'Joey Hong');
INSERT INTO characters (id, name) VALUES ('2042', 'Rita Muldoon');
INSERT INTO characters (id, name) VALUES ('2044', 'Dementor');
INSERT INTO characters (id, name) VALUES ('2046', 'Arisia');
INSERT INTO characters (id, name) VALUES ('2047', 'Martian Manhunter');
INSERT INTO characters (id, name) VALUES ('2048', 'Wonder Woman');
INSERT INTO characters (id, name) VALUES ('2049', 'The Ray');
INSERT INTO characters (id, name) VALUES ('2050', 'Captain Atom');
INSERT INTO characters (id, name) VALUES ('2051', 'Ice');
INSERT INTO characters (id, name) VALUES ('2053', 'Gerard Gardner');
INSERT INTO characters (id, name) VALUES ('2054', 'Ted Kord');
INSERT INTO characters (id, name) VALUES ('2055', 'General Glory (Jones)');
INSERT INTO characters (id, name) VALUES ('2060', 'Boodikka');
INSERT INTO characters (id, name) VALUES ('2061', 'Lord Blaze');
INSERT INTO characters (id, name) VALUES ('2062', 'Stickfast');
INSERT INTO characters (id, name) VALUES ('2063', 'Rags');
INSERT INTO characters (id, name) VALUES ('2067', 'Fast Jack');
INSERT INTO characters (id, name) VALUES ('2068', 'Cooper');
INSERT INTO characters (id, name) VALUES ('2070', 'Venus Bluegenes');
INSERT INTO characters (id, name) VALUES ('2071', 'Father Miguel Bonavita');
INSERT INTO characters (id, name) VALUES ('2072', 'Oliver Stoker');
INSERT INTO characters (id, name) VALUES ('2074', 'Nathan West');
INSERT INTO characters (id, name) VALUES ('2075', 'Shane Vansen');
INSERT INTO characters (id, name) VALUES ('2076', 'Vanessa Damphousse');
INSERT INTO characters (id, name) VALUES ('2077', 'Paul Wang');
INSERT INTO characters (id, name) VALUES ('2078', 'Cooper Hawkes');
INSERT INTO characters (id, name) VALUES ('2079', 'T.C. McQueen');
INSERT INTO characters (id, name) VALUES ('2080', 'Lt Esau Harriman');
INSERT INTO characters (id, name) VALUES ('2083', 'Battlewagon');
INSERT INTO characters (id, name) VALUES ('2087', 'Felicia Campbell');
INSERT INTO characters (id, name) VALUES ('2088', 'Jake Alexander');
INSERT INTO characters (id, name) VALUES ('2089', 'Arena');
INSERT INTO characters (id, name) VALUES ('2092', 'Mathemanic');
INSERT INTO characters (id, name) VALUES ('2093', 'Impulse');
INSERT INTO characters (id, name) VALUES ('2094', 'Coronary');
INSERT INTO characters (id, name) VALUES ('2095', 'Asylum');
INSERT INTO characters (id, name) VALUES ('2096', 'Pretty Persuasions');
INSERT INTO characters (id, name) VALUES ('2097', 'Rage');
INSERT INTO characters (id, name) VALUES ('2098', 'Night Thrasher');
INSERT INTO characters (id, name) VALUES ('2101', 'Firestar');
INSERT INTO characters (id, name) VALUES ('2102', 'Flashburn');
INSERT INTO characters (id, name) VALUES ('2103', 'Turbo');
INSERT INTO characters (id, name) VALUES ('2104', 'Speedball');
INSERT INTO characters (id, name) VALUES ('2105', 'Nova');
INSERT INTO characters (id, name) VALUES ('2106', 'Terrax');
INSERT INTO characters (id, name) VALUES ('2110', 'Darkling');
INSERT INTO characters (id, name) VALUES ('2111', 'Darkhawk');
INSERT INTO characters (id, name) VALUES ('2112', 'Angel');
INSERT INTO characters (id, name) VALUES ('2113', 'Namorita');
INSERT INTO characters (id, name) VALUES ('2114', 'Thing');
INSERT INTO characters (id, name) VALUES ('2115', 'Crystal');
INSERT INTO characters (id, name) VALUES ('2116', 'Chord');
INSERT INTO characters (id, name) VALUES ('2117', 'Sprocket');
INSERT INTO characters (id, name) VALUES ('2118', 'Sersi');
INSERT INTO characters (id, name) VALUES ('2119', 'Silhouette');
INSERT INTO characters (id, name) VALUES ('2120', 'Human Torch');
INSERT INTO characters (id, name) VALUES ('2122', 'Weapon Y');
INSERT INTO characters (id, name) VALUES ('2125', 'Sphinx');
INSERT INTO characters (id, name) VALUES ('2126', 'Rhino');
INSERT INTO characters (id, name) VALUES ('2127', 'Constrictor');
INSERT INTO characters (id, name) VALUES ('2128', 'Speed Demon');
INSERT INTO characters (id, name) VALUES ('2129', 'Stiletto');
INSERT INTO characters (id, name) VALUES ('2131', 'Mad Thinker');
INSERT INTO characters (id, name) VALUES ('2132', 'Primus');
INSERT INTO characters (id, name) VALUES ('2133', 'Skybreaker');
INSERT INTO characters (id, name) VALUES ('2134', 'Terraformer');
INSERT INTO characters (id, name) VALUES ('2135', 'Aqueduct');
INSERT INTO characters (id, name) VALUES ('2136', 'Quibble De Writ');
INSERT INTO characters (id, name) VALUES ('2137', 'Star Thief');
INSERT INTO characters (id, name) VALUES ('2138', 'Catseye');
INSERT INTO characters (id, name) VALUES ('2139', 'Beef');
INSERT INTO characters (id, name) VALUES ('2140', 'Tarot');
INSERT INTO characters (id, name) VALUES ('2141', 'Bevatron');
INSERT INTO characters (id, name) VALUES ('2142', 'Roulette');
INSERT INTO characters (id, name) VALUES ('2143', 'Jetstream');
INSERT INTO characters (id, name) VALUES ('2144', 'Bloodstrike');
INSERT INTO characters (id, name) VALUES ('2145', 'Smiling Tiger');
INSERT INTO characters (id, name) VALUES ('2146', 'Silk Fever');
INSERT INTO characters (id, name) VALUES ('2147', 'Left Hand');
INSERT INTO characters (id, name) VALUES ('2148', 'Tai');
INSERT INTO characters (id, name) VALUES ('2149', 'Galactus');