CREATE TABLE "genres" (
"id" INTEGER,
  "name" TEXT
)

INSERT INTO genres (id, name) VALUES ('40616', 'Pilipino Komiks');
INSERT INTO genres (id, name) VALUES ('40617', 'Alternate Reality');
INSERT INTO genres (id, name) VALUES ('40993', 'American Football');
INSERT INTO genres (id, name) VALUES ('41148', 'Green Lantern');
INSERT INTO genres (id, name) VALUES ('41709', 'Fastball Special');
INSERT INTO genres (id, name) VALUES ('42077', 'Hong Kong Manhua');
INSERT INTO genres (id, name) VALUES ('42287', 'Martial Arts');
INSERT INTO genres (id, name) VALUES ('42382', 'Comics Code Authority');
INSERT INTO genres (id, name) VALUES ('43049', 'Advertising in Comics');
INSERT INTO genres (id, name) VALUES ('43357', 'Women in Comics');
INSERT INTO genres (id, name) VALUES ('43598', 'British Comics');
INSERT INTO genres (id, name) VALUES ('43603', 'Manga');
INSERT INTO genres (id, name) VALUES ('43647', 'Çizgi Roman');
INSERT INTO genres (id, name) VALUES ('43721', 'Origin Stories in Comics');
INSERT INTO genres (id, name) VALUES ('43734', 'Homage Covers');
INSERT INTO genres (id, name) VALUES ('43738', 'Free Comic Book Day');
INSERT INTO genres (id, name) VALUES ('43763', 'Women in Refrigerators');
INSERT INTO genres (id, name) VALUES ('44158', 'Swimming');
INSERT INTO genres (id, name) VALUES ('44257', 'Jumping the Shark');
INSERT INTO genres (id, name) VALUES ('44517', 'Banda Desenhada');
INSERT INTO genres (id, name) VALUES ('44586', 'Elliniká Kómiks');
INSERT INTO genres (id, name) VALUES ('44795', 'Fourth Wall');
INSERT INTO genres (id, name) VALUES ('45747', 'Lettering in Comics');
INSERT INTO genres (id, name) VALUES ('45784', 'Comic Based Toys');
INSERT INTO genres (id, name) VALUES ('45787', 'Centerfold');
INSERT INTO genres (id, name) VALUES ('45806', 'Ikiman');
INSERT INTO genres (id, name) VALUES ('46699', 'Elseworlds');
INSERT INTO genres (id, name) VALUES ('46747', 'Stripverhaal');
INSERT INTO genres (id, name) VALUES ('47520', 'Bande Dessinée en France');
INSERT INTO genres (id, name) VALUES ('47795', 'Top Cow Pilot Season');
INSERT INTO genres (id, name) VALUES ('49473', 'M-Tech');
INSERT INTO genres (id, name) VALUES ('49870', 'Tecknade Serier');
INSERT INTO genres (id, name) VALUES ('50253', 'Manhwa');
INSERT INTO genres (id, name) VALUES ('50855', 'Danske Tegneserier');
INSERT INTO genres (id, name) VALUES ('52146', 'Historieta Colombiana');
INSERT INTO genres (id, name) VALUES ('52148', 'Eisner Awards');
INSERT INTO genres (id, name) VALUES ('55687', 'Buffyverse');
INSERT INTO genres (id, name) VALUES ('55701', 'Fantasy');
INSERT INTO genres (id, name) VALUES ('55706', 'Cricket');
INSERT INTO genres (id, name) VALUES ('55711', 'Continuity in Comics');
INSERT INTO genres (id, name) VALUES ('55712', 'Time Travel');
INSERT INTO genres (id, name) VALUES ('55720', 'Polskie Komiksy');
INSERT INTO genres (id, name) VALUES ('55721', 'Deutscher Comics');
INSERT INTO genres (id, name) VALUES ('55757', 'Cómics Mexicanos');
INSERT INTO genres (id, name) VALUES ('55766', 'Stargate');
INSERT INTO genres (id, name) VALUES ('55772', 'Tokusatsu');
INSERT INTO genres (id, name) VALUES ('55776', 'Gender Change');
INSERT INTO genres (id, name) VALUES ('55803', 'Crossover');
INSERT INTO genres (id, name) VALUES ('55811', 'Promotional Comic');
INSERT INTO genres (id, name) VALUES ('55826', 'Bowling');
INSERT INTO genres (id, name) VALUES ('55839', 'Motion Comic');
INSERT INTO genres (id, name) VALUES ('55841', 'Arechi');
INSERT INTO genres (id, name) VALUES ('55865', 'Variant Exclusive: WonderCon');
INSERT INTO genres (id, name) VALUES ('55871', 'Sarjakuva');
INSERT INTO genres (id, name) VALUES ('55883', 'Comics-Unrelated Cover');
INSERT INTO genres (id, name) VALUES ('55892', 'Fumetti Erotici d''Epoca');
INSERT INTO genres (id, name) VALUES ('55898', 'Historieta en España');
INSERT INTO genres (id, name) VALUES ('55906', 'View Askewniverse');
INSERT INTO genres (id, name) VALUES ('55907', 'Cosplay');
INSERT INTO genres (id, name) VALUES ('55913', 'Swimsuit Issue');
INSERT INTO genres (id, name) VALUES ('55914', 'First Wave');
INSERT INTO genres (id, name) VALUES ('55918', 'Open Source Character');
INSERT INTO genres (id, name) VALUES ('55925', 'Australian Comics');
INSERT INTO genres (id, name) VALUES ('55937', 'Second Feature');
INSERT INTO genres (id, name) VALUES ('55952', 'Fumetti');
INSERT INTO genres (id, name) VALUES ('55953', 'Esoterica in Comics');
INSERT INTO genres (id, name) VALUES ('55968', 'Ignatz Awards');
INSERT INTO genres (id, name) VALUES ('55969', 'Small Press Expo (SPX)');
INSERT INTO genres (id, name) VALUES ('55975', 'Harvey Awards');
INSERT INTO genres (id, name) VALUES ('55999', 'Homosexuality in Comics');
INSERT INTO genres (id, name) VALUES ('56004', 'Assistant Editors'' Month');
INSERT INTO genres (id, name) VALUES ('56007', 'Pro-Wrestling');
INSERT INTO genres (id, name) VALUES ('56010', 'Ice Skating');
INSERT INTO genres (id, name) VALUES ('56015', 'Cyberpunk');
INSERT INTO genres (id, name) VALUES ('56040', '3-D');
INSERT INTO genres (id, name) VALUES ('56041', 'Star Trek');
INSERT INTO genres (id, name) VALUES ('56042', 'Dancing');
INSERT INTO genres (id, name) VALUES ('56052', 'Screen Comix');
INSERT INTO genres (id, name) VALUES ('56054', 'Black Comedy');
INSERT INTO genres (id, name) VALUES ('56061', 'The New 52');
INSERT INTO genres (id, name) VALUES ('56075', 'Marvel''s Greatest Comics');
INSERT INTO genres (id, name) VALUES ('56079', 'Superpowers');
INSERT INTO genres (id, name) VALUES ('56081', 'Eagle Awards');
INSERT INTO genres (id, name) VALUES ('56085', 'Digital Comic');
INSERT INTO genres (id, name) VALUES ('56086', 'New Line Cinema');
INSERT INTO genres (id, name) VALUES ('56089', 'Marvel Cinematic Universe');
INSERT INTO genres (id, name) VALUES ('56090', 'Marriage');
INSERT INTO genres (id, name) VALUES ('56094', 'Wizard ½ Comics');
INSERT INTO genres (id, name) VALUES ('56100', 'Xeric Foundation');
INSERT INTO genres (id, name) VALUES ('56104', 'Inkpot Award');
INSERT INTO genres (id, name) VALUES ('56107', 'Variant Theme: Marvel Apes');
INSERT INTO genres (id, name) VALUES ('56108', 'Marvel Zombies');
INSERT INTO genres (id, name) VALUES ('56111', 'Gratis Comic Tag');
INSERT INTO genres (id, name) VALUES ('56122', 'Bill Finger Award');
INSERT INTO genres (id, name) VALUES ('56123', 'Taiwan Manhua');
INSERT INTO genres (id, name) VALUES ('56129', 'Marvel NOW!');
INSERT INTO genres (id, name) VALUES ('56137', 'Weirdoverse');
INSERT INTO genres (id, name) VALUES ('56140', 'Motorcycle Racing');
INSERT INTO genres (id, name) VALUES ('56141', 'The New 52: Zero Month');
INSERT INTO genres (id, name) VALUES ('56142', '''Nuff Said');