CREATE TABLE "publishers" (
"id" INTEGER,
  "name" TEXT
)

INSERT INTO publishers (id, name) VALUES ('4', 'Dell');
INSERT INTO publishers (id, name) VALUES ('5', 'United Feature Syndicate');
INSERT INTO publishers (id, name) VALUES ('8', 'Fiction House');
INSERT INTO publishers (id, name) VALUES ('10', 'DC Comics');
INSERT INTO publishers (id, name) VALUES ('14', 'David McKay');
INSERT INTO publishers (id, name) VALUES ('15', 'Quality Comics');
INSERT INTO publishers (id, name) VALUES ('18', 'Fox Comics (US)');
INSERT INTO publishers (id, name) VALUES ('20', 'Harvey');
INSERT INTO publishers (id, name) VALUES ('22', 'Eastern Color');
INSERT INTO publishers (id, name) VALUES ('24', 'Shogakukan-Shueisha Production');
INSERT INTO publishers (id, name) VALUES ('31', 'Marvel');
INSERT INTO publishers (id, name) VALUES ('32', 'Ace Magazines');
INSERT INTO publishers (id, name) VALUES ('34', 'Fawcett Publications');
INSERT INTO publishers (id, name) VALUES ('37', 'Hillman');
INSERT INTO publishers (id, name) VALUES ('45', 'Prize');
INSERT INTO publishers (id, name) VALUES ('46', 'Street and Smith');
INSERT INTO publishers (id, name) VALUES ('52', 'Lev Gleason');
INSERT INTO publishers (id, name) VALUES ('53', 'Doumei Shuppansha');
INSERT INTO publishers (id, name) VALUES ('55', 'Sekai Bunkasha');
INSERT INTO publishers (id, name) VALUES ('57', 'Gilberton Publications');
INSERT INTO publishers (id, name) VALUES ('68', 'Cat Wild');
INSERT INTO publishers (id, name) VALUES ('81', 'Thirdline');
INSERT INTO publishers (id, name) VALUES ('84', 'Magazine Enterprises');
INSERT INTO publishers (id, name) VALUES ('86', 'Spark Publications');
INSERT INTO publishers (id, name) VALUES ('87', 'Spotlight Publishers');
INSERT INTO publishers (id, name) VALUES ('89', 'EC');
INSERT INTO publishers (id, name) VALUES ('91', 'Coamix');
INSERT INTO publishers (id, name) VALUES ('92', 'Chikuma Shobo');
INSERT INTO publishers (id, name) VALUES ('100', 'Sergio Bonelli Editore');
INSERT INTO publishers (id, name) VALUES ('101', 'Archie Comics');
INSERT INTO publishers (id, name) VALUES ('111', 'Brother Shobo');
INSERT INTO publishers (id, name) VALUES ('113', 'American Comics Group');
INSERT INTO publishers (id, name) VALUES ('117', 'Star Publications');
INSERT INTO publishers (id, name) VALUES ('120', 'Arnoldo Mondadori Editore');
INSERT INTO publishers (id, name) VALUES ('121', 'Avon');
INSERT INTO publishers (id, name) VALUES ('122', 'Cross Publications');
INSERT INTO publishers (id, name) VALUES ('123', 'Toby');
INSERT INTO publishers (id, name) VALUES ('125', 'Charlton');
INSERT INTO publishers (id, name) VALUES ('126', 'Youthful');
INSERT INTO publishers (id, name) VALUES ('127', 'Angel Bunko');
INSERT INTO publishers (id, name) VALUES ('130', 'Trojan Magazines');
INSERT INTO publishers (id, name) VALUES ('131', 'Ziff-Davis');
INSERT INTO publishers (id, name) VALUES ('132', 'Tokosha');
INSERT INTO publishers (id, name) VALUES ('133', 'Wakakusa Shobo');
INSERT INTO publishers (id, name) VALUES ('136', 'Superior Publishers Limited');
INSERT INTO publishers (id, name) VALUES ('139', 'Story Comics');
INSERT INTO publishers (id, name) VALUES ('141', 'ST Publications');
INSERT INTO publishers (id, name) VALUES ('142', 'Tsuru Shobo');
INSERT INTO publishers (id, name) VALUES ('143', 'Ajax Comics Group');
INSERT INTO publishers (id, name) VALUES ('144', 'Comic Media');
INSERT INTO publishers (id, name) VALUES ('145', 'Shinseikaku');
INSERT INTO publishers (id, name) VALUES ('147', 'Nagaoka Shoten');
INSERT INTO publishers (id, name) VALUES ('150', 'Dalmatian Press');
INSERT INTO publishers (id, name) VALUES ('152', 'Ikuei Shuppan');
INSERT INTO publishers (id, name) VALUES ('153', 'Sterling Comics');
INSERT INTO publishers (id, name) VALUES ('154', 'Ballantine Books');
INSERT INTO publishers (id, name) VALUES ('157', 'Gyosei Shobo');
INSERT INTO publishers (id, name) VALUES ('159', 'Non-Fictional');
INSERT INTO publishers (id, name) VALUES ('162', 'Argo Publications');
INSERT INTO publishers (id, name) VALUES ('167', 'Sato Pro');
INSERT INTO publishers (id, name) VALUES ('169', 'Gorakusha');
INSERT INTO publishers (id, name) VALUES ('171', 'I.W. Publishing');
INSERT INTO publishers (id, name) VALUES ('173', 'Warren');
INSERT INTO publishers (id, name) VALUES ('174', 'Carlsen Verlag');
INSERT INTO publishers (id, name) VALUES ('175', 'New American Library');
INSERT INTO publishers (id, name) VALUES ('178', 'Western Publishing');
INSERT INTO publishers (id, name) VALUES ('183', 'Gakudosha');
INSERT INTO publishers (id, name) VALUES ('184', 'Editoriale Corno');
INSERT INTO publishers (id, name) VALUES ('185', 'Edwin Aprill');
INSERT INTO publishers (id, name) VALUES ('186', 'Minori Shobo');
INSERT INTO publishers (id, name) VALUES ('189', 'Casa Editrice Dardo');
INSERT INTO publishers (id, name) VALUES ('191', 'Corriere Della Sera');
INSERT INTO publishers (id, name) VALUES ('194', 'Tower');
INSERT INTO publishers (id, name) VALUES ('195', 'Toho Tosho Shuppansha');
INSERT INTO publishers (id, name) VALUES ('196', 'Perú Comics');
INSERT INTO publishers (id, name) VALUES ('198', 'King Features Syndicate');
INSERT INTO publishers (id, name) VALUES ('202', 'Futami Shobo');
INSERT INTO publishers (id, name) VALUES ('203', 'Milson Publishing Co. Inc.');
INSERT INTO publishers (id, name) VALUES ('208', 'Max Bunker Press');
INSERT INTO publishers (id, name) VALUES ('209', 'Nostalgia Press');
INSERT INTO publishers (id, name) VALUES ('210', 'Wallace Wood');
INSERT INTO publishers (id, name) VALUES ('212', 'Sakura Shuppan');
INSERT INTO publishers (id, name) VALUES ('214', 'Skywald');
INSERT INTO publishers (id, name) VALUES ('217', 'Amorfo Comics');
INSERT INTO publishers (id, name) VALUES ('219', 'Crown Publishers');
INSERT INTO publishers (id, name) VALUES ('223', 'Magazine Management');
INSERT INTO publishers (id, name) VALUES ('224', 'Barbour Christian Comics');
INSERT INTO publishers (id, name) VALUES ('225', 'Casa Editrice Universo');
INSERT INTO publishers (id, name) VALUES ('229', 'Editrice Cenisio');
INSERT INTO publishers (id, name) VALUES ('230', 'Gebers Förlag AB');
INSERT INTO publishers (id, name) VALUES ('233', 'Last Gasp');
INSERT INTO publishers (id, name) VALUES ('234', 'Edizioni San Paolo');
INSERT INTO publishers (id, name) VALUES ('236', 'Kitchen Sink');
INSERT INTO publishers (id, name) VALUES ('238', 'Hemmets Journal AB');
INSERT INTO publishers (id, name) VALUES ('239', 'Soft Magic');
INSERT INTO publishers (id, name) VALUES ('242', 'Dover Publications');
INSERT INTO publishers (id, name) VALUES ('244', 'Scholastic Book Services');
INSERT INTO publishers (id, name) VALUES ('246', 'Carlsen Comics (DK)');
INSERT INTO publishers (id, name) VALUES ('247', 'Simon and Schuster');
INSERT INTO publishers (id, name) VALUES ('249', 'Bruce Hershenson');
