-- Clean Teams (id, name only)
INSERT INTO teams (id, name) VALUES (1800, 'The Hand');
INSERT INTO teams (id, name) VALUES (2171, 'Thunderiders');
INSERT INTO teams (id, name) VALUES (2508, 'Ani-Men');
INSERT INTO teams (id, name) VALUES (3173, 'X-Men');
INSERT INTO teams (id, name) VALUES (3191, 'Morlocks');
INSERT INTO teams (id, name) VALUES (3199, 'Hellions');
INSERT INTO teams (id, name) VALUES (3238, 'U-Foes');
INSERT INTO teams (id, name) VALUES (3480, 'HYDRA');
INSERT INTO teams (id, name) VALUES (3775, 'S.H.I.E.L.D.');
INSERT INTO teams (id, name) VALUES (3804, 'Fantastic Four');
INSERT INTO teams (id, name) VALUES (3806, 'Avengers');
INSERT INTO teams (id, name) VALUES (4101, 'Shogun Warriors');
INSERT INTO teams (id, name) VALUES (4296, 'Sentinels');
INSERT INTO teams (id, name) VALUES (4443, 'Stepford Cuckoos');
INSERT INTO teams (id, name) VALUES (4951, 'Damage Control');
INSERT INTO teams (id, name) VALUES (4987, 'Brood');
INSERT INTO teams (id, name) VALUES (5018, 'Weapon X Program');
INSERT INTO teams (id, name) VALUES (5701, 'Doom Patrol');
INSERT INTO teams (id, name) VALUES (5704, 'Outsiders');
INSERT INTO teams (id, name) VALUES (5712, 'Metal Men');
INSERT INTO teams (id, name) VALUES (6097, 'Imperial Guard');
INSERT INTO teams (id, name) VALUES (6331, 'Ewoks');
INSERT INTO teams (id, name) VALUES (6796, 'Bacchae');
INSERT INTO teams (id, name) VALUES (6889, 'Madmen');
INSERT INTO teams (id, name) VALUES (6905, 'Royal Flush Gang');
INSERT INTO teams (id, name) VALUES (6992, 'Green Lantern Corps');
INSERT INTO teams (id, name) VALUES (7115, 'Cabal of Scrier');
INSERT INTO teams (id, name) VALUES (7417, 'COBRA');
INSERT INTO teams (id, name) VALUES (7582, 'Masters of Evil');
INSERT INTO teams (id, name) VALUES (7588, 'Kree');
INSERT INTO teams (id, name) VALUES (7715, 'Dreadnoks');
INSERT INTO teams (id, name) VALUES (8178, 'Cylons');
INSERT INTO teams (id, name) VALUES (9057, 'Guardians of the Universe');
INSERT INTO teams (id, name) VALUES (9483, 'Code: Blue');
INSERT INTO teams (id, name) VALUES (9591, 'League of Assassins');
INSERT INTO teams (id, name) VALUES (9726, 'Reavers');
INSERT INTO teams (id, name) VALUES (9727, 'Upstarts');
INSERT INTO teams (id, name) VALUES (9730, 'Acolytes');
INSERT INTO teams (id, name) VALUES (10980, 'Micronauts');
INSERT INTO teams (id, name) VALUES (11285, 'White Martians');
INSERT INTO teams (id, name) VALUES (11427, 'Inhumans');
INSERT INTO teams (id, name) VALUES (11439, 'Frightful Four');
INSERT INTO teams (id, name) VALUES (11523, 'The Watchers');
INSERT INTO teams (id, name) VALUES (11879, 'Wild Pack');
INSERT INTO teams (id, name) VALUES (11896, 'New Warriors');
INSERT INTO teams (id, name) VALUES (12206, 'G.I. Joe');
INSERT INTO teams (id, name) VALUES (13011, 'Newsboy Legion');
INSERT INTO teams (id, name) VALUES (13343, 'Celestials');
INSERT INTO teams (id, name) VALUES (13344, 'Eternals');
INSERT INTO teams (id, name) VALUES (13345, 'Deviants');
INSERT INTO teams (id, name) VALUES (13357, 'Hellfire Club');
INSERT INTO teams (id, name) VALUES (13407, 'Atlanteans');
INSERT INTO teams (id, name) VALUES (13497, 'A.I.M.');
INSERT INTO teams (id, name) VALUES (13918, 'Rigellians');
INSERT INTO teams (id, name) VALUES (13930, 'Ovoids');
INSERT INTO teams (id, name) VALUES (13953, 'Megans');
INSERT INTO teams (id, name) VALUES (13986, 'Kronans');
INSERT INTO teams (id, name) VALUES (14015, 'Dire Wraiths');
INSERT INTO teams (id, name) VALUES (14245, 'Force Works');
INSERT INTO teams (id, name) VALUES (14616, 'Alpha Flight');
INSERT INTO teams (id, name) VALUES (14632, 'Omega Men');
INSERT INTO teams (id, name) VALUES (14821, 'Crazy Gang');
INSERT INTO teams (id, name) VALUES (14864, 'Excalibur');
INSERT INTO teams (id, name) VALUES (14871, 'Starjammers');
INSERT INTO teams (id, name) VALUES (14915, 'Purifiers');
INSERT INTO teams (id, name) VALUES (14999, 'Hellfire Soldiers');
INSERT INTO teams (id, name) VALUES (15025, 'The Goth');
INSERT INTO teams (id, name) VALUES (15083, 'Generation X');
INSERT INTO teams (id, name) VALUES (15136, 'Secret Empire');
INSERT INTO teams (id, name) VALUES (15344, 'New Men');
INSERT INTO teams (id, name) VALUES (15347, 'Gene Nation');
INSERT INTO teams (id, name) VALUES (15409, 'Factor Three');
INSERT INTO teams (id, name) VALUES (15521, 'People''''s Defense Force');
INSERT INTO teams (id, name) VALUES (15595, 'X-Force');
INSERT INTO teams (id, name) VALUES (15625, 'Great Beasts');
INSERT INTO teams (id, name) VALUES (15929, 'Wolfpack');
INSERT INTO teams (id, name) VALUES (15971, 'New Mutants');
INSERT INTO teams (id, name) VALUES (16341, 'Challengers of the Unknown');
